# Generated by Django 3.2.9 on 2021-11-23 16:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='goods name')),
                ('length', models.FloatField(default=0, verbose_name='fish length')),
                ('width', models.FloatField(default=0, verbose_name='fish width')),
                ('price', models.IntegerField(default=0, verbose_name='goods price')),
                ('brief', models.TextField(max_length=500, verbose_name='brief for goods')),
                ('description', models.TextField(max_length=10000, verbose_name='description for goods')),
                ('indexImage', models.ImageField(blank=True, null=True, upload_to='goods/indexImages', verbose_name='image for goods index')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/images', verbose_name='image')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goods', verbose_name='goods')),
            ],
            options={
                'verbose_name': 'all goods images',
                'verbose_name_plural': 'all goods images',
            },
        ),
    ]
